### ISSUE TITLE
HTTPS POST requests does not work

### ISSUE THREAD

**Issue by Sakvojage** [toitware/public#39]
**Describe the bug**
I am getting MALLOC errors on trying to post some JSON data:

```
EXCEPTION error. 
MALLOC_FAILED
  0: tls_handshake_            <sdk>/tls/session.toit:372:3
  1: Session.handshake.<block> <sdk>/tls/session.toit:108:9
  2: Session.handshake         <sdk>/tls/session.toit:86:3
  3: Session.ensure_handshaken_ <sdk>/tls/session.toit:191:5
  4: Session.write             <sdk>/tls/session.toit:140:5
  5: Socket.write              <sdk>/tls/socket.toit:91:21
  6: Writer.write              <sdk>/writer.toit:37:23
  ```

**To reproduce**
```
import ble
import certificate_roots
import http
import net
import net.x509
import encoding.json
import device

main:
  bd := ble.Device.default

  bd.scan: | bleDevice/ble.RemoteDevice |
    if bleDevice.data.manufacturer_data.size == 13 and bleDevice.data.manufacturer_data[0] == 0x9a and bleDevice.data.manufacturer_data[1] == 0x08 :
      post bleDevice
      sleep --ms=30000
      
post sensor:

  temperature := (sensor.data.manufacturer_data[4].to_float * 256 + sensor.data.manufacturer_data[5].to_float)/100
  if temperature > 255:
    temperature -= 655

  json_payload := {
    "t": temperature,
    "h": sensor.data.manufacturer_data[6].to_float,
    "b": 2000 + (sensor.data.manufacturer_data[12].to_float * 10),
    "mac" : sensor.address.stringify
  }

  network := net.open
  client := http.Client.tls network --root_certificates=[certificate_roots.ISRG_ROOT_X1]
  response := client.post_json json_payload --host="XXXXXXX.eu" --path="/sensors/ingest"

```

**SDK and console version (please complete the following information):**
```
Device ID: 5721d43a-f79d-41c6-9345-b8938cb9f207
Hardware ID: 86ef8f4b-0d72-4b60-98b2-5cdbe40a6517
Name: Tower A
Model: esp32-4mb
Firmware: v1.6.6
```

Impossible to use - not a single request succeeded.

**Comment by floitsch** [comment]
This should be fixed (or at least massively improved) with the latest version of Toit.

**Comment by AlexanderPilhar** [comment]
It seems this issue still exists!
Device is a M5Stack Core2.
```
[main.toit] MALLOC_FAILED
[main.toit]   0: tls_handshake_            <sdk>/tls/session.toit:372:3
[main.toit]   1: Session.handshake.<block> <sdk>/tls/session.toit:108:9
[main.toit]   2: Session.handshake         <sdk>/tls/session.toit:86:3
[main.toit]   3: Session.ensure_handshaken_ <sdk>/tls/session.toit:191:5
[main.toit]   4: Session.write             <sdk>/tls/session.toit:140:5
[main.toit]   5: Socket.write              <sdk>/tls/socket.toit:91:21
[main.toit]   6: Writer.write              <sdk>/writer.toit:37:23
[main.toit]   7: Connection.send_headers   <pkg:pkg-http>/connection.toit:47:13
[main.toit]   8: Request.send              <pkg:pkg-http>/request.toit:38:32
[main.toit]   9: Client.post               <pkg:pkg-http>/client.toit:151:20
[main.toit]  10: Client.post_json          <pkg:pkg-http>/client.toit:172:12
[main.toit]  11: change_status             /d:/my-project/main.toit:63:27
[main.toit]  12: main                      /d:/my-project/main.toit:101:7
[main.toit]  13: __entry__.<lambda>        <sdk>/core/entry.toit:48:20
```
```
Model: esp32-4mb
Firmware: v1.6.9
```
```
CERTIFICATES ::= [certificate_roots.GO_DADDY_CLASS_2_CA, certificate_roots.GO_DADDY_ROOT_CERTIFICATE_AUTHORITY_G2]
http_client := http.Client.tls network --root_certificates=CERTIFICATES
response := http_client.post_json --host=URL --path=PATH data
```
NOTE: There is no issue when using HTTP without TLS:
```
http_client := http.Client network
response := http_client.post_json --host=URL --path=PATH data
```

**Comment by floitsch** [comment]
Could you give us the URL you are trying to connect to?
thanks.

**Comment by AlexanderPilhar** [comment]
The URL is core.poinow.info.

**Comment by kasperl** [comment]
Hi @AlexanderPilhar. Thank you so much for the bug report. Can you confirm that the problem still exists with v1.6.11 of the firmware (just released)?

**Comment by AlexanderPilhar** [comment]
Yes, the problem still exists with v1.6.11.
```
[main.toit] Successfully installed Toit SDK (version: v1.6.11) locally.
[main.toit] 2022-04-28T07:37:16.356743Z: <stack trace>
[main.toit] EXCEPTION error. 
[main.toit] MALLOC_FAILED
[main.toit]   0: tls_handshake_            <sdk>/tls/session.toit:372:3
[main.toit]   1: Session.handshake.<block> <sdk>/tls/session.toit:108:9
[main.toit]   2: Session.handshake         <sdk>/tls/session.toit:86:3
[main.toit]   3: Session.ensure_handshaken_ <sdk>/tls/session.toit:191:5
[main.toit]   4: Session.write             <sdk>/tls/session.toit:140:5
[main.toit]   5: Socket.write              <sdk>/tls/socket.toit:91:21
[main.toit]   6: Writer.write              <sdk>/writer.toit:37:23
[main.toit]   7: Connection.send_headers   <pkg:pkg-http>/connection.toit:47:13
[main.toit]   8: Request.send              <pkg:pkg-http>/request.toit:38:32
[main.toit]   9: Client.post               <pkg:pkg-http>/client.toit:151:20
[main.toit]  10: Client.post_json          <pkg:pkg-http>/client.toit:172:12
[main.toit]  11: change_status             /d:/my-project/main.toit:563:30
[main.toit]  12: on_touch_up               /d:/my-project/main.toit:618:11
[main.toit]  13: main                      /d:/my-project/main.toit:731:9
[main.toit]  14: __entry__.<lambda>        <sdk>/core/entry.toit:48:20
```

**Comment by kasperl** [comment]
Thanks, @AlexanderPilhar!

**Comment by floitsch** [comment]
I just tried with the following example with the latest version (1.6.18):
```
import net
import certificate_roots
import tls
import http

HOST ::= "core.poinow.info"
PORT ::= 443

main:
  network := net.open
  client := http.Client.tls network
      --root_certificates=[certificate_roots.GO_DADDY_CLASS_2_CA, certificate_roots.GO_DADDY_ROOT_CERTIFICATE_AUTHORITY_G2]

  response := client.get HOST --port=PORT "/debug"
  print response.status_code
  data := #[]
  while chunk := response.body.read:
    data += chunk
  print data.to_string
```

The status code is 302 (redirect) which probably goes to a 404 page.
However, I believe that the TLS connection is already established when that happens. If that's the case, then Toit should be able to connect to the server now.

**Comment by AlexanderPilhar** [comment]
Still fails with latest version (1.6.18)
```
EXCEPTION error. 
MALLOC_FAILED
  0: tls_handshake_            <sdk>/tls/session.toit:372:3
  1: Session.handshake.<block> <sdk>/tls/session.toit:108:9
  2: Session.handshake         <sdk>/tls/session.toit:86:3
  3: Session.ensure_handshaken_ <sdk>/tls/session.toit:191:5
  4: Session.write             <sdk>/tls/session.toit:140:5
  5: Socket.write              <sdk>/tls/socket.toit:91:21
  6: Writer.write              <sdk>/writer.toit:37:23
  7: Connection.send_headers   <pkg:pkg-http>/connection.toit:47:13
  8: Request.send              <pkg:pkg-http>/request.toit:38:32
  9: Client.post               <pkg:pkg-http>/client.toit:151:20
 10: Client.post_json          <pkg:pkg-http>/client.toit:172:12
 11: change_status             /d:/my-project/main.toit:581:30
 12: on_touch_up               /d:/my-project/main.toit:636:11
 13: main                      /d:/my-project/main.toit:765:9
 14: __entry__.<lambda>        <sdk>/core/entry.toit:48:20
```

**Comment by floitsch** [comment]
Could you maybe send me the code so I can do some experiments? (florian@toit.io).
Ideally with an API call that isn't doing anything nefarious.

**Comment by floitsch** [comment]
This was already shared with Alexander, but for the record:

I looked through the code, and the device is simply running out of memory.
There are two connections already (One for toit.io, and one for mqtt). Adding a third one, that uses TLS is a bit too much.

The setup works correctly on the open-source version as that one doesn't automatically use a TLS connection, and is generally leaner.

**Comment by floitsch** [comment]
Closing.
The solution is to migrate to Toit 2.0  (open-source), where we have a better GC and generally use less memory.
